float1 = 12345678901234567.0
float2 = 123456789001234568.0
result_a = float1 - float2
print(result_a)

# Result is -1.111111101e+17.


int1 = 12345678901234567
int2 = 123456789001234568
result_b = int1 - int2
print(result_b)

# Result is -111111110100000001


#Both results (result_a and result_b) are the same value, but result_a is shown with float numbers (following the scientific notation), because result_b is generated by subtracting two other float numbers (float1 and float2)
